model:
  n_layer: 1
  n_head: 1
  n_embd: 256
  linear: True

data:
  name: 'window'
  min_num: 1
  max_num: 16
  k: 2
  p: 17
  sep: 17
  cot: False
  num_tokens: 16
  n_train: 256
  n_test: 64
  fixed_len: True

train:
  lr: 0.0001 
  att_scale_c: 10.0
  att_jump_step: 50
  grad_clip: -1
  num_steps: 400
  norm_type: "none_rank"
  wandb: True
  save_ckpt: False
  ckpt_freq: 20
